[package]
name = "eval_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.10.0"
actix-web = "4.9.0"
serde = "1.0.213"
config = "0.14.1"
derive-ctor = "1.0.6"
indexmap = "2.7.0"

[dependencies.rustbreak]
version = "2"
features = ["ron_enc"]

[[bin]]
name = "api"